<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "datamints_error_report"
 *
 * Auto generated by Extension Builder 2021-12-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'datamints Error Report',
    'description' => 'sends bundled error-log entries by email',
    'category' => 'services',
    'author' => 'Mark Weisgerber',
    'author_email' => 'm.weisgerber@datamints.com',
    'state' => 'stable',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
